New exception on <%= link_to @link, @link %><br /><br />

<div class="date">
	<%= @e.created_at.to_s(:exc_full) %>
</div>
<h1>
<%= @e.exception_class %> in <%= @e.controller_name.camelcase %>/<%= @e.action_name %>
</h1>

<h2>Request</h2>

<div class="request">
  <%= h(@e.request).gsub(/\n/,"<br />") %>
</div>

<h2>Backtrace</h2>

<%= simple_format h(@e.message) %>

<div id="backtrace">
<%=h(@e.backtrace).gsub(/\n/,"<br />") %>
</div>

<h2>Environment</h2>

<%= h(@e.environment).gsub(/\n/,"<br />") %>